### ISSUE TITLE
User Auth Review

### ISSUE THREAD

**Issue by Droool** [Droool/OpenCounter#2]
- [x] Users can sign up, sign in, log out
- [x]   Users can use a demo login to try the site
- [x]   Users can't use certain features without logging in (creating reservations or reviews)
- [x]   Completely styled and seeded

**Comment by jliversi** [comment]
Great job overall, and the functionality is all perfect, just a few notes on styling: 

- [ ] Your modal forms are a little too wide currently, reduce their width by like 40px
- [ ] Change the placeholders for your sign-in form to exactly match those on openTable.
- [ ] Slightly reduce the size of the text in your form inputs.
- [ ] Instead of hardcoding the width of your image/it's darkening background div, set it to 100vw so it's just the width of the viewport. 
- [ ] Slightly increase the top padding on your navBar to pull the elements a few pixels farther from the top of the page.

**Comment by Droool** [comment]
Hey Josh, I've made the corrections you've asked. The only thing is I can't give it 100vw as it stretches all the way to the far right of the page; making it inconsistent with their background image.
